"""Context-enriched chunker — Anthropic's approach from the book (Ch. 3).

Each chunk is prepended with a concise context summary generated by an LLM,
providing situational grounding.  This technique reduced retrieval failures
by 49% in Anthropic's testing.
"""

from __future__ import annotations

import asyncio
from typing import Any

from ragmax.core.models import Chunk, Document
from ragmax.core.protocols import LLMProvider

CONTEXT_PROMPT = """<document>
{doc_content}
</document>

Here is the chunk we want to situate within the whole document:
<chunk>
{chunk_content}
</chunk>

Please give a short succinct context to situate this chunk within the overall document
for the purposes of improving search retrieval of the chunk. Answer only with the
succinct context and nothing else."""


class ContextEnrichedChunker:
    """Enrich chunks with LLM-generated context summaries.

    First splits the document using a base chunker (recursive by default),
    then prepends each chunk with a context description generated by an LLM.
    """

    def __init__(
        self,
        llm: LLMProvider | None = None,
        chunk_size: int = 512,
        chunk_overlap: int = 64,
        max_doc_preview: int = 4000,
        **kwargs: Any,
    ) -> None:
        self.llm = llm
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.max_doc_preview = max_doc_preview

    def chunk(self, document: Document) -> list[Chunk]:
        """Synchronous entry point."""
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            # Fall back to base chunking without enrichment
            return self._base_chunk(document)
        return asyncio.run(self._chunk_async(document))

    async def _chunk_async(self, document: Document) -> list[Chunk]:
        base_chunks = self._base_chunk(document)

        if self.llm is None:
            return base_chunks

        # Truncated document preview for context generation
        doc_preview = document.content[: self.max_doc_preview]

        enriched: list[Chunk] = []
        for chunk in base_chunks:
            prompt = CONTEXT_PROMPT.format(
                doc_content=doc_preview,
                chunk_content=chunk.content,
            )
            try:
                context = await self.llm.generate([{"role": "user", "content": prompt}])
                enriched_content = f"{context.strip()}\n\n{chunk.content}"
            except Exception:
                enriched_content = chunk.content

            enriched.append(
                Chunk(
                    id=chunk.id,
                    content=enriched_content,
                    document_id=chunk.document_id,
                    index=chunk.index,
                    metadata={**chunk.metadata, "chunker": "context_enriched"},
                )
            )
        return enriched

    def _base_chunk(self, document: Document) -> list[Chunk]:
        from ragmax.chunking.recursive import RecursiveChunker

        base = RecursiveChunker(
            chunk_size=self.chunk_size,
            chunk_overlap=self.chunk_overlap,
        )
        return base.chunk(document)
